java_package: oracle-java8-installer
spark_version: 1.5.2
zeppelin_spark_version: 1.5
spark_download_url: http://d3kbcqa49mib13.cloudfront.net
apt_repos:
maven_version: 3.3.9
maven_download_url: http://wwwftp.ciril.fr
spark_notebook_version: 0.6.3
